name: wamp_client
description: A library for WAMP protocol client.  WAMP is the Web Application Messaging Protocol (https://wamp-proto.org)
version: 0.3.0
homepage: https://github.com/kkazuo/dart-wamp-client

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  web_socket_channel: ^1.0.9

dev_dependencies:
  test: ^1.16.8
